services:
  - type: web
    name: crimelens-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: admin@crimelens.com
      - key: ADMIN_PASSWORD
        value: Admin@123
      - key: CORS_ORIGIN
        value: "*"
