/**
 * Alert Model - System notifications and crime alerts
 * Critical for: Real-time notifications, proactive policing
 */

const mongoose = require('mongoose');

const alertSchema = new mongoose.Schema({
  // Basic Information
  title: {
    type: String,
    required: [true, 'Alert title is required'],
    trim: true
  },
  description: {
    type: String,
    required: [true, 'Description is required']
  },
  
  // Alert Type
  type: {
    type: String,
    enum: [
      'crime_alert',
      'warning',
      'information',
      'emergency',
      'pattern_detected',
      'risk_prediction',
      'system_alert',
      'maintenance'
    ],
    required: true
  },
  severity: {
    type: String,
    enum: ['low', 'medium', 'high', 'critical'],
    required: true
  },
  
  // Alert Origin
  source: {
    type: {
      type: String,
      enum: ['system', 'ai', 'manual', 'user', 'external']
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    systemName: String,
    autoGenerated: {
      type: Boolean,
      default: false
    }
  },
  
  // Crime Context
  crime: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'CrimeIncident'
  },
  location: {
    district: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'District'
    },
    policeStation: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'PoliceStation'
    },
    coordinates: {
      type: {
        type: String,
        enum: ['Point']
      },
      coordinates: [Number]
    },
    address: String
  },
  
  // AI/ML Context
  aiContext: {
    trigger: String,
    confidence: Number,
    prediction: String,
    dataPoints: [String],
    modelVersion: String
  },
  
  // Alert Action
  recommendedAction: {
    type: String,
    enum: ['investigate', 'patrol', 'warn', 'evacuate', 'monitor', 'none']
  },
  actionDetails: String,
  priority: {
    type: Number,
    min: 1,
    max: 10,
    default: 5
  },
  
  // Recipients
  recipients: [{
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    role: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Role'
    },
    delivered: {
      type: Boolean,
      default: false
    },
    read: {
      type: Boolean,
      default: false
    },
    readAt: Date,
    acknowledged: {
      type: Boolean,
      default: false
    },
    acknowledgedAt: Date
  }],
  broadcast: {
    type: Boolean,
    default: false
  },
  
  // Delivery Channels
  delivery: {
    sms: {
      sent: Boolean,
      recipients: [String]
    },
    email: {
      sent: Boolean,
      recipients: [String]
    },
    inApp: {
      sent: Boolean,
      read: Boolean
    },
    push: {
      sent: Boolean,
      devices: [String]
    },
    dashboard: {
      displayed: Boolean,
      dismissed: Boolean
    }
  },
  
  // Alert Timeline
  timeline: [{
    status: {
      type: String,
      enum: ['created', 'dispatched', 'delivered', 'read', 'acknowledged', 'action_taken', 'resolved']
    },
    timestamp: {
      type: Date,
      default: Date.now
    },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    note: String
  }],
  
  // Resolution
  resolution: {
    status: {
      type: String,
      enum: ['pending', 'in_progress', 'resolved', 'false_alarm', 'ignored']
    },
    resolvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    resolvedAt: Date,
    resolutionNotes: String,
    actionsTaken: [String]
  },
  
  // Geographic Scope
  scope: {
    type: String,
    enum: ['national', 'state', 'district', 'station', 'local']
  },
  
  // Expiry
  expiresAt: Date,
  isExpired: {
    type: Boolean,
    default: false
  },
  
  // Status
  status: {
    type: String,
    enum: ['draft', 'active', 'dispatched', 'acknowledged', 'resolved', 'expired'],
    default: 'draft'
  },
  
  // Audit
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  updatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, {
  timestamps: true
});

// ============================================
// Indexes
// ============================================
alertSchema.index({ severity: 1, status: 1 });
alertSchema.index({ 'location.district': 1 });
alertSchema.index({ 'recipients.user': 1 });
alertSchema.index({ expiresAt: 1 });
alertSchema.index({ createdAt: -1 });

// ============================================
// Static Methods
// ============================================
alertSchema.statics.getActiveAlerts = function() {
  return this.find({
    status: { $in: ['active', 'dispatched'] },
    isExpired: false,
    expiresAt: { $gt: new Date() }
  }).sort({ priority: -1, severity: -1 });
};

alertSchema.statics.getAlertsForUser = function(userId) {
  return this.find({
    'recipients.user': userId,
    status: { $ne: 'draft' }
  }).sort({ createdAt: -1 });
};

// ============================================
// Instance Methods
// ============================================
alertSchema.methods.markRead = function(userId) {
  const recipient = this.recipients.find(r => r.user.toString() === userId.toString());
  if (recipient) {
    recipient.read = true;
    recipient.readAt = new Date();
    this.timeline.push({ status: 'read', user: userId });
  }
  return this.save();
};

alertSchema.methods.acknowledge = function(userId, note) {
  const recipient = this.recipients.find(r => r.user.toString() === userId.toString());
  if (recipient) {
    recipient.acknowledged = true;
    recipient.acknowledgedAt = new Date();
    this.timeline.push({ status: 'acknowledged', user: userId, note });
  }
  return this.save();
};

const Alert = mongoose.model('Alert', alertSchema);

module.exports = Alert;